config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'search/search'
  get "home/map" => "homes#map"
  get "/search" => "searches#search"
  get "reviews/area" => "reviews#area"

  resources :reviews do
    resource :favorites, only: [:create, :destroy]
    resources :review_comments, only: [:create, :destroy]
  end

  resources :tags do
    get 'reviews', to: 'reviews#search'
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    member do
      get :like
    end
  end
 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :reviews, dependent: :destroy
  has_many :review_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  # フォロー機能
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  validates :name, presence: true
  validates :email, uniqueness: true

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews.page(params[:page]).per(9).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'ユーザーの編集完了しました！'
      redirect_to user_path(@user.id)
    else
      flash.now[:danger] = 'ユーザーの編集に失敗しました'
      render :edit
    end
  end

  def like
    reviews_ids = Favorite.where(user_id: params[:id]).pluck(:review_id)
    @reviews = Review.where(id: reviews_ids).page(params[:page]).per(12).reverse_order
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_info.html.erb
<!--フォローフォロワーボタン-->
<% if current_user.following?(user) %>
  <%= link_to "フォロー解除", user_relationships_path(user.id), method: :delete %>
<% else %>
  <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
<% end %>

app/views/users/edit.html.erb
<!--プロフィール編集画面-->
<div class="container">
  <div class="row mb-4 text-center">
    <div class="col-sm-12">
      <h4>プロフィール編集</h4>
    </div>
  </div>
  
  <!--フラッシュメッセージ-->
  <div class="row text-center">
    <div class="font col-sm-12">
      <p class="flash"><%= flash[:danger] %></p>
      <% if @user.errors.any? %>
        <p class="flash"><%= @user.errors.count %>件のエラーが発生しました</p>
      <% end %>
    </div>
  </div>
  
  <!--編集フォーム-->
  <%= form_with model: @user, local:true do |f| %>
    <div class="row text-center">
      <div class="col-sm-12">
        <label>名前</label>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
      </div>
    </div>
    <div class="row text-center">
      <div class="col-sm-12">
        <label>プロフィール画像</label>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "20200503_noimage.jpg", size: "100x100" %>
      </div>
    </div>
    <div class="row text-center mt-2">
      <div class="col-sm-12">
        <%= f.submit "変更を保存", class: "btn btn-success col-sm-2" %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/like.html.erb
<!--いいねした記事一覧表示-->
<div class="container">
  <div class="row mb-4 text-center">
    <div class="col-sm-12">
      <h4>いいねしたレビュー</h4>
    </div>
  </div>
  
  <% if @reviews.exists? %>
    <div class="row">
      <%= render 'reviews/review', reviews: @reviews %>
    </div>
  <% else %>
    <div class="row text-center">
      <div class="font col-sm-12">
        <h5>投稿レビューはありません</h5>
      </div>
    </div>
  <% end %>
  
  <!--ページャ機能-->
  <%= paginate @reviews %>
</div>

app/views/users/show.html.erb
<!--ユーザー詳細ページ-->
<div class="container">
  <div class="row text-center mb-4">
    <div class="col-sm-12">
      <h4 class="profile-name"><%= @user.name %>さんのプロフィール</h4>
    </div>
  </div>
  
  <!--フラッシュメッセージ-->
  <div class="row text-center">
    <div class="font col-sm-12">
      <% if flash[:success] %>
        <p class="flash"><%= flash[:success] %></p>
      <% end %>
    </div>
  </div>

  <!--プロフィール編集・フォロー機能-->
  <div class="row text-left">
    <div class="col-sm-3 offset-sm-2">
      <strong>プロフィール画像</strong>
      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "20200503_noimage.jpg", size: "100x100" %>
    </div>
    <% if user_signed_in? %>
    <div class="col-sm-2 my-auto">
      <% if @user == current_user %>
        <%= link_to "", edit_user_path(@user), class: 'fas fa-user-cog btn btn-outline-dark col-sm-12' %>
      <% end %>
      <% unless @user == current_user %>
        <% if current_user.following?(@user) %>
          <%= link_to "フォローを外す", user_relationships_path(@user.id), method: :delete, class: 'btn btn-success' %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: 'btn btn-success' %>
        <% end %>
      <% end %>
    </div>
    <% end %>

    <!--フォローフォロワー数-->
    <div class="relation col-sm-5">
      <div class="friend">
        <%= link_to user_followings_path(@user) do %>
        <label><i class="far fa-handshake"></i> フォロー</label>
          <%= @user.followings.count %>
          人
        <% end %>
      </div>
      <div class="friend">
        <%= link_to user_followers_path(@user) do %>
        <label><i class="fas fa-handshake"></i> フォロワー</label>
          <%= @user.followers.count %>
          人
        <% end %>
      </div>
      <% if @user == current_user %>
      <div div class="friend">
        <%= link_to like_user_path(@user) do %>
        <label class="book-mark"><i class="fas fa-bookmark"></i> いいねしたレビュー</label>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>

  <!--ユーザーの投稿-->
  <div class="row text-center mt-5 mb-4">
    <div class="col-sm-12">
      <h4 class="profile-name"><%= @user.name %>さんの投稿記事</h4>
    </div>
  </div>
  
  <% if @reviews.exists? %>
  <div class="row text-center">
    <% @reviews.each do |review| %>
      <div class="men col-sm-4 mb-4 py-3">
        <%= link_to review_path(review.id) do %>
          <%= attachment_image_tag review, :image, :fill, 250, 150, fallback: "22047646_s.jpg", size: "250x150" %>
          <p class="shop">店名：<%= review.shop_name %></p>
        <% end %>
        <div>評価</div>
        <div class="review-evaluation" data-score="<%= review.evaluation %>"></div>
        <i class="far fa-comment-dots"></i>
        <%= link_to "#{review.review_comments.count} コメント", review_path(review.id) %>
        <div>
        <% review.tags.each do |tag| %>
        <i class="far fa-bookmark"></i>
          <%= link_to tag_reviews_path(tag.id) do %>
            <%= tag.tag_name %>
          <% end %>
        <% end %>
      </div>
      </div>
    <% end %>
  </div>
  <% else %>
  <div class="row text-center">
    <div class="font col-sm-12">
      <h5>投稿レビューはありません</h5>
    </div>
  </div>
  <% end %>

  <!--ページャ機能-->
  <%= paginate @reviews %>
</div>