config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'search/search'
  get "home/map" => "homes#map"
  get "/search" => "searches#search"
  get "reviews/area" => "reviews#area"

  resources :reviews do
    resource :favorites, only: [:create, :destroy]
    resources :review_comments, only: [:create, :destroy]
  end

  resources :tags do
    get 'reviews', to: 'reviews#search'
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    member do
      get :like
    end
  end
 
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @all_ranks = Review.find(Favorite.group(:review_id).order('count(review_id) desc').limit(6).pluck(:review_id))
    if @all_ranks == nil
       @all_ranks = []
    end
  end

  def map
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/map.html.erb
<!--イメージマップ-->
<div class="container">
  <div class="row mb-4 text-center">
    <div class="col-sm-12">
      <h4>地域を選択してください</h>
    </div>
  </div>

  <div id="map1"><%= image_tag "22043060.jpg", usemap: "#ImageMap" %>
    <map name="ImageMap">
      <area shape="rect" coords="572,36,806,169" href="<%= reviews_area_path(id: 0) %>" alt="北海道地方" />
      <area shape="rect" coords="567,181,651,330" href="<%= reviews_area_path(id: 1) %>" alt="東北地方" />
      <area shape="rect" coords="537,333,623,395" href="<%= reviews_area_path(id: 2) %>" alt="関東地方" />
      <area shape="rect" coords="445,318,532,404" href="<%= reviews_area_path(id: 3) %>" alt="中部地方" />
      <area shape="rect" coords="374,372,445,445" href="<%= reviews_area_path(id: 4) %>" alt="関西地方" />
      <area shape="rect" coords="231,376,367,421" href="<%= reviews_area_path(id: 5) %>" alt="中国地方" />
      <area shape="rect" coords="291,421,374,467" href="<%= reviews_area_path(id: 6) %>" alt="四国地方" />
      <area shape="rect" coords="184,431,282,524" href="<%= reviews_area_path(id: 7) %>" alt="九州地方" />
      <area shape="rect" coords="666,453,758,543" href="<%= reviews_area_path(id: 7) %>" alt="九州地方" />
    </map>
  </div>
</div>

<script>
 $(function() {
  $('img[usemap]').rwdImageMaps();
 })
</script>

app/views/homes/top.html.erb
<!--トップページ-->
<div class="container">
  <div class="row mb-5 d-flex align-items-center text-center">
    <div class="col-sm-6">
      <h3 class="top-text pt-5 py-1">
        ラーメンを食べるのが好き！</br>
        美味しいラーメンを探したい！</br>
        お店のラーメンの味が知りたい！</br>
        </br>
        そんなあなたの力になります
      </h3>
      <p class="about">※ログインしないとレビューの投稿・編集・削除、いいね、フォロー機能は使用できません</p>
    </div>
    <div class="slide col-sm-6">
      <%= image_tag "4647665_s.jpg" %>
      <%= image_tag "4919466_s.jpg" %>
      <%= image_tag "5193999_s.jpg" %>
    </div>
  </div>
  
  <div class="row mb-4 text-center">
    <div class="col-sm-12">
      <h4>人気レビューランキング</h4>
    </div>
  </div>
 
  <!--ランキングのレビュー表示-->
  <div class="row text-center">
  <% @all_ranks.each.with_index(1) do |review, i| %>
    <div class="men col-sm-4 mb-5 py-3">
      <p class="rank">
        <i class="fas fa-crown"></i>
        第<%= i %>位
      </p>
      <%= link_to review_path(review.id) do %>
        <%= attachment_image_tag review, :image, :fill, 170, 100, fallback: "22047646_s.jpg", size: "170x100" %>
        <p class="text">店名：<%= review.shop_name %></p>
      <% end %>
      <div>評価</div>
      <div class="review-evaluation" data-score="<%= review.evaluation %>"></div>
      <%= link_to user_path(review.user.id) do %>
      <p class="text"><i class="fas fa-user-edit"></i><%= review.user.name %></p>
      <% end %>
      <div><%= attachment_image_tag review.user, :profile_image, :fill, 40, 40, fallback: "20200503_noimage.jpg", size: "40x40" %></div>
      <i class="far fa-comment-dots"></i>
      <%= link_to "#{review.review_comments.count} コメント", review_path(review.id) %>
      <div>
        <% review.tags.each do |tag| %>
        <i class="far fa-bookmark"></i>
          <%= link_to tag_reviews_path(tag.id) do %>
            <%= tag.tag_name %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
  </div>
</div>