config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'search/search'
  get "home/map" => "homes#map"
  get "/search" => "searches#search"
  get "reviews/area" => "reviews#area"

  resources :reviews do
    resource :favorites, only: [:create, :destroy]
    resources :review_comments, only: [:create, :destroy]
  end

  resources :tags do
    get 'reviews', to: 'reviews#search'
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    member do
      get :like
    end
  end
 
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @tag_list = params[:review][:tag_name].split(/[[:blank:]]+/)
    if @review.save
      @review.save_tag(@tag_list)
      flash[:success] = 'レビュー新規投稿完了しました！'
      redirect_to reviews_path
    else
      flash.now[:danger] = 'レビュー新規登録に失敗しました'
      render :new
    end
  end

  def index
    @tag_lists = Tag.all
    @reviews = Review.all.page(params[:page]).per(12).reverse_order
    if @reviews == nil
       @reviews = []
    end
  end

  def show
    @review = Review.find(params[:id])
    @post_tags = @review.tags
    @review_comment = ReviewComment.new
  end

  def edit
    @review = Review.find(params[:id])
    @review.tag_name = @review.tags.pluck(:tag_name).join(' ')
  end

  def update
    @review = Review.find(params[:id])
    @tag_list = params[:review][:tag_name].split(/[[:blank:]]+/)
    if @review.update(review_params)
      @review.update_tag(@tag_list)
      flash[:success] = 'レビュー編集完了しました！'
      redirect_to review_path(@review.id)
    else
      flash.now[:danger] = 'レビューの編集に失敗しました'
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to reviews_path
  end

  def search
    @tag = Tag.find(params[:tag_id])
    @reviews = @tag.review.all.page(params[:page]).per(12).reverse_order
    if @reviews == nil
       @reviews = []
    end
  end

  def area
    @area_name = Review.areas.keys[params[:id].to_i]
    @reviews = Review.where(area: params[:id]).page(params[:page]).per(12).reverse_order
  end

  private

  def review_params
    params.require(:review).permit(:shop_name, :image, :caption, :evaluation).merge(area: params[:review][:area].to_i)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<!--レビュー投稿・編集フォーム-->
<%= form_with model: review, local:true do |f| %>
  <div class="row">
    <div class="col-sm-10 offset-sm-2">
      <table class="table-borderless-review">
        <tr>
          <div>
            <td><%= f.label :店舗・料理画像 %></td>
            <td><%= f.attachment_field :image %></td>
          </div>
        </tr>
        <tr>
          <div>
            <td><%= f.label :店名 %></td>
            <td><%= f.text_field :shop_name, class:"form-control", placeholder: "店名を記入してください" %></td>
          </div>
        </tr>
        <tr>
          <div>
            <td><%= f.label :レビュー %></td>
            <td><%= f.text_area :caption, size: "x5", class:"form-control", placeholder: "レビューを記入してください" %></td>
          </div>
        </tr>
        <tr>
          <div>
            <td><%= f.label :地域選択 %></td>
            <td><%= f.select :area, options_for_select(Review.areas), {prompt: "選択してください"} %></td>
          </div>
        </tr>
        <tr>
          <td><%= f.label :評価 %></td>
          <td>
             <div id="evaluate_stars"></div>
          </td>
        </tr>
        <tr>
          <td></td>
          <td>※スペースをつけることで複数のタグを設定できます</td>
        </tr>
        <tr>
          <div>
            <td><%= f.label :タグ設定 %></td>
            <td><%= f.text_field :tag_name, class:"form-control", placeholder: "タグを記入してください" %></td>
          </div>
        </tr>
      </table>
    </div>
  </div>
  
  <div class="row text-center my-4">
    <dev class="col-sm-12">
      <%= f.submit '投稿', class: 'btn btn-success col-sm-2' %>
    </dev>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<!--レビューのbody-->
<% reviews.each do |review| %>
  <div class="men col-sm-4 mb-5 py-3 text-center">
    <%= link_to review_path(review.id) do %>
      <%= attachment_image_tag review, :image, :fill, 250, 150, fallback: "22047646_s.jpg", size: "250x150" %>
      <p class="text">店名：<%= review.shop_name %></p>
    <% end %>
    <div>評価</div>
    <div class="review-evaluation" data-score="<%= review.evaluation %>"></div>
    <%= link_to user_path(review.user.id) do %>
    <p class="text"><i class="fas fa-user-edit"></i><%= review.user.name %></p>
    <% end %>
    <div><%= attachment_image_tag review.user, :profile_image, :fill, 40, 40, fallback: "20200503_noimage.jpg", size: "40x40" %></div>
    <i class="far fa-comment-dots"></i>
    <%= link_to "#{review.review_comments.count} コメント", review_path(review.id) %>
    <div>
      <% review.tags.each do |tag| %>
      <i class="fas fa-tag"></i></i>
        <%= link_to tag_reviews_path(tag.id) do %>
          <%= tag.tag_name %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/reviews/area.html.erb
<!--イメージマップからの絞り込みページ-->
<div class="container">
  <div class="row mb-4 text-center">
    <div class="col-sm-12">
      <h4><%= @area_name %>のレビュー</h>
    </div>
  </div>

  <% if @reviews.exists? %>
    <div class="row">
      <%= render 'reviews/review', reviews: @reviews %>
    </div>
   <% else %>
    <div class="row text-center">
      <div class="font col-sm-12">
        <h5>投稿レビューはありません</h5>
      </div>
    </div>
  <% end %>

  <!--ページャ機能-->
  <%= paginate @reviews %>
</div>

app/views/reviews/edit.html.erb
<!--レビュー編集機能-->
<div class="container">
  <div class="row mb-4 text-center">
    <div class="col-sm-12">
      <h4>レビュー編集</h>
    </div>
  </div>
  
  <!--フラッシュメッセージ-->
  <div class="row text-center">
    <div class="font col-sm-12">
      <p class="flash"><%= flash[:danger] %></p>
      <% if @review.errors.any? %>
        <p class="flash"><%= @review.errors.count %>件のエラーが発生しました</p>
      <% end %>
    </div>
  </div>
  
  <!--編集フォーム-->
  <%= render 'reviews/form', review: @review %>
  
  <script>
    $('#evaluate_stars').raty({
      starOn: "<%= asset_path('star-on.png') %>",
      starOff: "<%= asset_path('star-off.png') %>",
      starHalf: "<%= asset_path('star-half.png') %>",
      scoreName: 'review[evaluation]'
    });
  </script>
</div>

app/views/reviews/index.html.erb
<!--レビュー一覧表示-->
<div class="container">
  <div class="row mb-4 text-center">
    <div class="col-sm-12">
      <h4>レビュー一覧</h4>
    </div>
  </div>
  
  <!--フラッシュメッセージ-->
  <div class="row text-center">
    <div class="font col-sm-12">
      <% if flash[:success] %>
        <p class="flash"><%= flash[:success] %></p>
      <% end %>
    </div>
  </div>
  
  <div class="row">
    <%= render 'reviews/review', reviews: @reviews %>
  </div>
  
  <!--ページャ機能-->
  <%= paginate @reviews %>
</div>

app/views/reviews/new.html.erb
<!--レビュー新規投稿機能-->
<div class="container">
  <div class="row mb-4 text-center">
    <div class="col-sm-12">
      <h4>レビュー新規投稿</h>
    </div>
  </div>
  
  <!--フラッシュメッセージ-->
  <div class="row text-center">
    <div class="font col-sm-12">
      <%= flash[:danger] %>
      <% if @review.errors.any? %>
        <p class="flash"><%= @review.errors.count %>件のエラーが発生しました</p>
      <% end %>
    </div>
  </div>
  
  <!--投稿フォーム-->
  <%= render 'reviews/form', review: @review %>
        
  <script>
    $('#evaluate_stars').raty({
      starOn: "<%= asset_path('star-on.png') %>",
      starOff: "<%= asset_path('star-off.png') %>",
      starHalf: "<%= asset_path('star-half.png') %>",
      scoreName: 'review[evaluation]'
    });
  </script>
</div>

app/views/reviews/search.html.erb
<!--タグ検索後の表示-->
<div class="container">
  <div class="row mb-4 text-center">
    <div class="col-sm-12">
      <h4>タグが<strong><%= "#{@tag.tag_name}" %></strong>の投稿一覧</h4>
    </div>
  </div>
  
  <!--タグ検索後のレビュー-->
  <div class="row">
    <%= render 'reviews/review', reviews: @reviews %>
  </div>

  <!--ページャ機能-->
  <%= paginate @reviews %>
</div>

app/views/reviews/show.html.erb
<!--レビュー詳細-->
<div class="container">
  
  <!--フラッシュメッセージ-->
  <div class="row text-center">
    <div class="font col-sm-12">
      <% if flash[:success] %>
        <p class="flash"><%= flash[:success] %></p>
      <% end %>
    </div>
  </div>
  
  <!--レビュー詳細-->
  <div class="row mb-4">
    <div class="font col-sm-5 text-center">
      <%= attachment_image_tag @review, :image, :fill, 300, 200, fallback: "22047646_s.jpg", size: "300x200" %>
      <p class="shop">店名：<%= @review.shop_name %></p>
      <div>評価</div>
      <p class="review-evaluation" data-score="<%= @review.evaluation %>"></p>
      <p class="text-body">レビュー<%= simple_format(h(@review.caption)) %></p>
      <p><i class="fas fa-map-marker-alt"></i>:<%= @review.area %></p>
      <%= link_to user_path(@review.user.id) do %>
      <p><i class="fas fa-user-edit"></i>:<%= @review.user.name %></p>
      <% end %>
      
      <!--いいね機能-->
      <% if user_signed_in? %>
      <div class="favorite_button_<%= @review.id %>">
        <%= render 'favorites/favorite', review: @review %>
      </div>
      <% end %>
      <p class="time"><i class="fas fa-clock"></i>:<%= @review.created_at.strftime('%Y/%m/%d') %></p>
      
      <!--編集・削除ボタン-->
      <% if user_signed_in? %>
        <% if @review.user == current_user %>
          <%= link_to "編集", edit_review_path(@review), class:'btn btn-success' %>
          <%= link_to "削除", review_path(@review), method: :delete, class:'btn btn-danger' %>
        <% end %>
      <% end %>
    </div>
    
    <!--レビューへのコメント一覧-->
    <div class="font col-sm-7">
      <i class="far fa-comment-dots"></i>
      コメント件数：<%= @review.review_comments.count %>件
      <% @review.review_comments.each do |review_comment| %>
        <p class="comment"<%= simple_format(h(review_comment.comment)) %></p>
        <p>
          <%= attachment_image_tag review_comment.user, :profile_image, :fill, 40, 40, fallback: "20200503_noimage.jpg", size: "40x40" %>
          <%= review_comment.user.name %>
          <i class="time"><%= review_comment.created_at.strftime('%Y/%m/%d %H:%M') %></i>
          <!--コメント削除機能-->
          <% if review_comment.user == current_user %>
            <%= link_to "削除", review_review_comment_path(review_comment.review, review_comment), method: :delete, class:'btn btn-danger' %>
          <% end %>
        </p>
      <% end %>

      <!--コメント投稿フォーム-->
      <% if user_signed_in? %>
        <%= form_with(model:[@review, @review_comment], local: true) do |f| %>
          <%= f.text_area :comment, size: "60x5", placeholder: "コメントをここに書いてください" %>
          <p class="text-center">
            <%= f.submit "書き込む", class: 'btn btn-success col-sm-2' %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>