config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'search/search'
  get "home/map" => "homes#map"
  get "/search" => "searches#search"
  get "reviews/area" => "reviews#area"

  resources :reviews do
    resource :favorites, only: [:create, :destroy]
    resources :review_comments, only: [:create, :destroy]
  end

  resources :tags do
    get 'reviews', to: 'reviews#search'
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    member do
      get :like
    end
  end
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/review.rb
class Review < ApplicationRecord
  attachment :image

  attr_accessor :tag_name

  belongs_to :user
  has_many :review_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps, dependent: :destroy

  validates :image, presence: true
  validates :shop_name, presence: true
  validates :caption, presence: true
  validates :area, presence: true
  validates :evaluation, presence: true

  enum area: {
    北海道地方: 0, 東北地方: 1, 関東地方: 2, 中部地方: 3, 関西地方: 4, 中国地方: 5, 四国地方: 6, 九州地方: 7
  }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def save_tag(sent_tags)
    current_tags = tags.pluck(:tag_name) unless tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_tag = Tag.find_or_create_by(tag_name: new)
      tags << new_tag
    end
  end

  def update_tag(sent_tags)
    current_tags = tags.pluck(:tag_name) unless tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_tag = Tag.find_or_create_by(tag_name: new)
      tags << new_tag
    end
  end
end

app/models/review_comment.rb
class ReviewComment < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_maps, dependent: :destroy, foreign_key: 'tag_id'
  has_many :review, through: :tag_maps
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :review
  belongs_to :tag

  validates :review_id, presence: true
  validates :tag_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :reviews, dependent: :destroy
  has_many :review_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  # フォロー機能
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  validates :name, presence: true
  validates :email, uniqueness: true

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @all_ranks = Review.find(Favorite.group(:review_id).order('count(review_id) desc').limit(6).pluck(:review_id))
    if @all_ranks == nil
       @all_ranks = []
    end
  end

  def map
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @tag_list = params[:review][:tag_name].split(/[[:blank:]]+/)
    if @review.save
      @review.save_tag(@tag_list)
      flash[:success] = 'レビュー新規投稿完了しました！'
      redirect_to reviews_path
    else
      flash.now[:danger] = 'レビュー新規登録に失敗しました'
      render :new
    end
  end

  def index
    @tag_lists = Tag.all
    @reviews = Review.all.page(params[:page]).per(12).reverse_order
    if @reviews == nil
       @reviews = []
    end
  end

  def show
    @review = Review.find(params[:id])
    @post_tags = @review.tags
    @review_comment = ReviewComment.new
  end

  def edit
    @review = Review.find(params[:id])
    @review.tag_name = @review.tags.pluck(:tag_name).join(' ')
  end

  def update
    @review = Review.find(params[:id])
    @tag_list = params[:review][:tag_name].split(/[[:blank:]]+/)
    if @review.update(review_params)
      @review.update_tag(@tag_list)
      flash[:success] = 'レビュー編集完了しました！'
      redirect_to review_path(@review.id)
    else
      flash.now[:danger] = 'レビューの編集に失敗しました'
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to reviews_path
  end

  def search
    @tag = Tag.find(params[:tag_id])
    @reviews = @tag.review.all.page(params[:page]).per(12).reverse_order
    if @reviews == nil
       @reviews = []
    end
  end

  def area
    @area_name = Review.areas.keys[params[:id].to_i]
    @reviews = Review.where(area: params[:id]).page(params[:page]).per(12).reverse_order
  end

  private

  def review_params
    params.require(:review).permit(:shop_name, :image, :caption, :evaluation).merge(area: params[:review][:area].to_i)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def search
    @model = params["search"]["model"]
    @value = params["search"]["value"]
    @how = params["search"]["how"]
    @datas = search_for(@how, @model, @value)
  end
  
  private
  
  def match(model, value)
    if model == 'user'
      User.where(name: value)
    elsif model == 'review'
      Review.where(shop_name: value)
    end
  end
  
  def partical(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    elsif model == 'review'
      Review.where("shop_name LIKE ?", "%#{value}%")
    end
  end
  
  def search_for(how, model, value)
    case how
    when 'match'
      match(model, value)
    when 'partical'
      partical(model, value)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews.page(params[:page]).per(9).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'ユーザーの編集完了しました！'
      redirect_to user_path(@user.id)
    else
      flash.now[:danger] = 'ユーザーの編集に失敗しました'
      render :edit
    end
  end

  def like
    reviews_ids = Favorite.where(user_id: params[:id]).pluck(:review_id)
    @reviews = Review.where(id: reviews_ids).page(params[:page]).per(12).reverse_order
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/review_comments_helper.rb
module ReviewCommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダー-->
  　<header>
      <div class="container">
        <nav class="navbar navbar-expand-lg">
            <%= link_to root_path do %>
              <%= image_tag "logo.png", class: "logo" %>
            <% end %>
          <div class="collapse navbar-collapse">
            <div class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="category ml-4">
                <i class="far fa-compass"></i>
                <%= link_to '地域検索', home_map_path, class: 'text-dark' %>
              </li>
              <li class="category ml-4">
                <i class="far fa-user"></i>
                <%= link_to 'マイページ', user_path(current_user.id), class: 'text-dark' %>
              </li>
              <li class="category ml-4">
                <i class="far fa-comments"></i>
                <%= link_to "レビュー", reviews_path, class: 'text-dark' %>
                </li>
              <li class="category ml-4">
                <i class="fas fa-pen"></i>
                <%= link_to "レビュー投稿", new_review_path, class: 'text-dark' %>
              </li>
              <li class="category mx-4">
                <i class="fas fa-sign-out-alt"></i>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'text-dark' %>
              </li>
            <% else %>
              <li class="category ml-4">
                <i class="far fa-compass"></i>
                <%= link_to '地域検索', home_map_path, class: 'text-dark' %>
              </li>
              <li class="category ml-4">
                <i class="far fa-comments"></i>
                <%= link_to "レビュー", reviews_path, class: 'text-dark' %>
              </li>
              <li class="category ml-4">
                <i class="fas fa-user-plus"></i>
                <%= link_to "新規登録", new_user_registration_path, class: 'text-dark' %>
              </li>
              <li class="category ml-4">
                <i class="fas fa-sign-in-alt"></i>
                <%= link_to "ログイン", new_user_session_path, class: 'text-dark' %>
              </li>
            <% end %>
              <div>
                <% if user_signed_in? %>
                  <%= form_with url:search_path, method: :get, local: true do |f| %>
                    <%= f.text_field 'search[value]', placeholder: "店名検索" %>
                    <%= button_tag :type => "submit", :name => nil,　class: "button is-info" do %>
                    <i class="fas fa-search"></i>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </nav>
        <div class="col-sm-9">
          <% if user_signed_in? %>
            <p>ようこそ、<%= current_user.name %>さん！</p>
          <% end %>
        </div>
      </div>
    </header>

    <!--本文-->
    <main>
      <div class="mb-auto py-2">
        <%= yield %>
      </div>
      
      <!--フラッシュメッセージのフェードアウト-->
      <script>
        $(function() {
          setTimeout("$('.flash').fadeOut('slow')", 2000);
        });
      </script>
      
      <!--星評価表示-->
      <script>
      $('.review-evaluation').empty();
        $('.review-evaluation').raty({
          readOnly: true,
          score: function() {
            return $(this).attr('data-score');
          },
          starOff: "<%= asset_path('star-off.png') %>",
          starOn: "<%= asset_path('star-on.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>"
        });
      </script>
    </main>
    
  </body>
</html>